#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-codenarc
Version  : 0.25.2
Release  : 2
URL      : https://github.com/CodeNarc/CodeNarc/archive/v0.25.2.tar.gz
Source0  : https://github.com/CodeNarc/CodeNarc/archive/v0.25.2.tar.gz
Source1  : https://repo.gradle.org/gradle/libs-releases/org/codenarc/CodeNarc/0.25.2/CodeNarc-0.25.2.jar
Source2  : https://repo.gradle.org/gradle/libs-releases/org/codenarc/CodeNarc/0.25.2/CodeNarc-0.25.2.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-codenarc-data = %{version}-%{release}
Requires: mvn-codenarc-license = %{version}-%{release}
BuildRequires : buildreq-mvn
BuildRequires : gradle

%description
# CodeNarc  (http://codenarc.org/)
**CodeNarc** is a static analysis tool for Groovy source code, enabling monitoring and enforcement of many coding standards and best practices. CodeNarc applies a set of Rules (predefined and/or custom) that are applied to each Groovy file, and generates an HTML or XML report of the results, including a list of rules violated for each source file, and a count of the number of violations per package and for the whole project.

%package data
Summary: data components for the mvn-codenarc package.
Group: Data

%description data
data components for the mvn-codenarc package.


%package license
Summary: license components for the mvn-codenarc package.
Group: Default

%description license
license components for the mvn-codenarc package.


%prep
%setup -q -n CodeNarc-0.25.2

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-codenarc
cp LICENSE.txt %{buildroot}/usr/share/package-licenses/mvn-codenarc/LICENSE.txt
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codenarc/CodeNarc/0.25.2
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/codenarc/CodeNarc/0.25.2/CodeNarc-0.25.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codenarc/CodeNarc/0.25.2
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/codenarc/CodeNarc/0.25.2/CodeNarc-0.25.2.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/codenarc/CodeNarc/0.25.2/CodeNarc-0.25.2.jar
/usr/share/java/.m2/repository/org/codenarc/CodeNarc/0.25.2/CodeNarc-0.25.2.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-codenarc/LICENSE.txt
